version: '3'

services:
  saenai-blog:
    build: .
    restart: always
    container_name: saenai-blog
    environment:
      TZ: 'Asia/Shanghai'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:8080'  
